name: 'Lock down repository'

on:
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          pr-comment: >
            This repository does not accept pull requests now.
            Submission period will be open from '2020-09-30T20:00:00'
